version: '3.4'

services:
  focusbot:
    image: focusbot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"